/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erhannis.theallforum.client;

import com.erhannis.theallforum.Context;
import com.erhannis.theallforum.data.Handle;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author erhannis
 */
public class ClientFrame extends javax.swing.JFrame {
  private Context ctx;
  private RestClient restClient;
  private Handle userHandle;
  private String username;
  private String password; //TODO Should probably log in once and exchange for token...maybe

  /**
   * Creates new form ClientFrame
   */
  public ClientFrame(Context ctx) {
    this.ctx = ctx;
    this.restClient = new RestClient(ctx);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSplitPane1 = new javax.swing.JSplitPane();
    jPanel1 = new javax.swing.JPanel();
    btnLogInOut = new javax.swing.JButton();
    lUsername = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jSplitPane1.setDividerLocation(150);

    btnLogInOut.setText("Log In");
    btnLogInOut.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLogInOutActionPerformed(evt);
      }
    });

    lUsername.setText("(Anonymous)");

    jButton1.setText("jButton1");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(btnLogInOut)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lUsername))
          .addComponent(jButton1))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnLogInOut)
          .addComponent(lUsername))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1)
        .addContainerGap(454, Short.MAX_VALUE))
    );

    jSplitPane1.setLeftComponent(jPanel1);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 520, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 522, Short.MAX_VALUE)
    );

    jSplitPane1.setRightComponent(jPanel2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnLogInOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInOutActionPerformed
    logInOut();
  }//GEN-LAST:event_btnLogInOutActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
      System.out.println(restClient.events());
    } catch (IOException ex) {
      Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  private void logInOut() {
    if (userHandle == null) {
      // Log in
      JPanel panel = new JPanel();
      //JLabel label = new JLabel("Enter a password:");
      JTextField tfUsername = new JTextField();
      JPasswordField pfPassword = new JPasswordField(20);
      //panel.add(label);
      panel.add(tfUsername);
      panel.add(pfPassword);
      String[] options = new String[]{"OK", "Cancel"};
      int option = JOptionPane.showOptionDialog(null, panel, "Log in",
              JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
              null, options, options[1]);
      if (option == 0) // pressing OK button
      {
        String newUsername = tfUsername.getText();
        char[] newPassword = pfPassword.getPassword();
        
      }
    } else {
      // Log out
      //TODO Dunno if the server needs to be informed
      userHandle = null;
      username = null;
      password = null; //TODO Maybe clear out bytes or whatever
    }
    updateLoginStatus();
  }

  private void updateLoginStatus() {
    if (userHandle == null) {
      // Logged out
      btnLogInOut.setText("Log in");
      lUsername.setText("(Anonymous)");
    } else {
      // Logged in
      btnLogInOut.setText("Log out");
      lUsername.setText(username);
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLogInOut;
  private javax.swing.JButton jButton1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JLabel lUsername;
  // End of variables declaration//GEN-END:variables
}
