/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erhannis.theallforum.client;

import com.erhannis.theallforum.Context;
import com.erhannis.theallforum.data.Handle;
import com.erhannis.theallforum.data.Signature;
import com.erhannis.theallforum.data.events.Event;
import com.erhannis.theallforum.data.events.post.PostCreated;
import com.erhannis.theallforum.data.events.user.UserCreated;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.SignatureException;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.CLOSED_OPTION;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author erhannis
 */
public class ClientFrame extends javax.swing.JFrame {
  private Context ctx;
  private RestClient restClient;
  private Handle userHandle;
  private String username;
  private String password; //TODO Should probably log in once and exchange for token...maybe

  /**
   * Creates new form ClientFrame
   */
  public ClientFrame(Context ctx) {
    this.ctx = ctx;
    this.restClient = new RestClient(ctx);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSplitPane1 = new javax.swing.JSplitPane();
    jPanel1 = new javax.swing.JPanel();
    btnLogInOut = new javax.swing.JButton();
    lUsername = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel3 = new javax.swing.JPanel();
    btnCreatePost = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    taCreatePostText = new javax.swing.JTextArea();
    jPanel2 = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jSplitPane1.setDividerLocation(150);

    btnLogInOut.setText("Log In");
    btnLogInOut.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLogInOutActionPerformed(evt);
      }
    });

    lUsername.setText("(Anonymous)");

    jButton1.setText("jButton1");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(btnLogInOut)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lUsername))
          .addComponent(jButton1))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnLogInOut)
          .addComponent(lUsername))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1)
        .addContainerGap(504, Short.MAX_VALUE))
    );

    jSplitPane1.setLeftComponent(jPanel1);

    btnCreatePost.setText("Post");
    btnCreatePost.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCreatePostActionPerformed(evt);
      }
    });

    taCreatePostText.setColumns(20);
    taCreatePostText.setRows(5);
    jScrollPane1.setViewportView(taCreatePostText);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(btnCreatePost)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnCreatePost)
        .addContainerGap())
    );

    jTabbedPane1.addTab("CreatePost", jPanel3);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 572, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 537, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("tab2", jPanel2);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 572, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 537, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("tab3", jPanel4);

    jSplitPane1.setRightComponent(jTabbedPane1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnLogInOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInOutActionPerformed
    logInOut();
  }//GEN-LAST:event_btnLogInOutActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
      List<Event> events = restClient.events();
      for (Event e : events) {
        if (e instanceof UserCreated) {
          boolean success = false;
          try {
            success = Signature.verifyUser(ctx, e, ((UserCreated) e).userSignature.value, ((UserCreated) e).publicKey);
          } catch (IllegalAccessException ex) {
            Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
          } catch (InvalidKeyException ex) {
            Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SignatureException ex) {
            Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
          } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
          } catch (IllegalArgumentException ex) {
            Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
          } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
          System.out.println("Signature correct for: " + ((UserCreated) e).username);
        }
      }
    } catch (IOException ex) {
      Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  private void btnCreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePostActionPerformed
    createPost();
  }//GEN-LAST:event_btnCreatePostActionPerformed

  private void logInOut() {
    if (userHandle == null) {
      // Log in
      JPanel panel = new JPanel();
      JTextField tfUsername = new JTextField();
      JPasswordField pfPassword = new JPasswordField(20);
      panel.setLayout(new java.awt.GridLayout(0, 2));
      panel.add(new JLabel("Username"));
      panel.add(tfUsername);
      panel.add(new JLabel("Password"));
      panel.add(pfPassword);
//      String[] options = new String[]{"OK", "Cancel"};
//      tfUsername.requestFocus();
//      int option = JOptionPane.showOptionDialog(null, panel, "Log in",
//              JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
//              null, options, options[0]);
      JOptionPane pane = new JOptionPane(panel, JOptionPane.QUESTION_MESSAGE, JOptionPane.OK_CANCEL_OPTION) {
        @Override
        public void selectInitialValue() {
          tfUsername.requestFocusInWindow();
        }
      };
      pane.createDialog(null, "Log in").setVisible(true);
      String[] options = null;
      int option;
      result_block: { // Copied from JOptionPane.showOptionDialog
        Object selectedValue = pane.getValue();
        if (selectedValue == null) {
          option = CLOSED_OPTION;
          break result_block;
        }
        if (options == null) {
          if (selectedValue instanceof Integer) {
            option = ((Integer) selectedValue).intValue();
            break result_block;
          }
          option = CLOSED_OPTION;
          break result_block;
        }
        for (int counter = 0, maxCounter = options.length;
                counter < maxCounter; counter++) {
          if (options[counter].equals(selectedValue)) {
            option = counter;
            break result_block;
          }
        }
        option = CLOSED_OPTION;
        break result_block;
      }
      if (option == 0) // pressing OK button
      {
        String newUsername = tfUsername.getText();
        String newPassword = new String(pfPassword.getPassword());
        try {
          Handle newUserHandle = restClient.login(newUsername, newPassword);
          if (newUserHandle != null) {
            username = newUsername;
            userHandle = newUserHandle;
            password = newPassword;
          } else {
            JOptionPane.showMessageDialog(null, "Invalid login");
          }
        } catch (IOException ex) {
          Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
          JOptionPane.showMessageDialog(null, "Error logging in");
        }
      }
    } else {
      // Log out
      //TODO Dunno if the server needs to be informed
      userHandle = null;
      username = null;
      password = null; //TODO Maybe clear out bytes or whatever
    }
    updateLoginStatus();
  }

  private void updateLoginStatus() {
    if (userHandle == null) {
      // Logged out
      btnLogInOut.setText("Log in");
      lUsername.setText("(Anonymous)");
    } else {
      // Logged in
      btnLogInOut.setText("Log out");
      lUsername.setText(username);
    }
  }

  private void createPost() {
    if (userHandle == null) {
      JOptionPane.showMessageDialog(null, "Please log in first.");
      return;
    }
    PostCreated post = new PostCreated();
    post.handle = Handle.gen();
    post.parents = new HashSet<>();
    post.previous = new HashSet<>();
    post.tags = new HashSet<>();
    post.text = taCreatePostText.getText();
    post.user = userHandle;
    
    try {
      Event event = restClient.postEvent(userHandle, password, post);
      //TODO Store locally
      if (event == null) {
        throw new IOException("Event was null");
      }
    } catch (IOException ex) {
      Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, "Please log in first.");
      return;
    }
    
    // Reset for new post
    taCreatePostText.setText("");
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCreatePost;
  private javax.swing.JButton btnLogInOut;
  private javax.swing.JButton jButton1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JLabel lUsername;
  private javax.swing.JTextArea taCreatePostText;
  // End of variables declaration//GEN-END:variables
}
